# Database Workflow - Schema Design & Migration
#
# This workflow designs complete database schema with RLS policies,
# indexes, and creates migration files.

name: database
description: Design database schema, migrations, and RLS policies

prerequisites:
  - supabase_configured
  - drizzle_orm_installed
  - migrations_directory_exists

agents:
  - name: pm-agent
    agent_file: .claude/agents/planning/pm-agent.md
    input: "Gather data requirements if not already documented"
    output: data-requirements.md
    parallel: false
    skip_if: requirements_exist

  - name: database-architect
    agent_file: .claude/agents/implementation/database-architect.md
    input: "Design complete database schema with tables, RLS policies, indexes, and migration file"
    output: schema-design.md
    parallel: false

post_workflow:
  - save_migration_file
  - update_drizzle_schema
  - update_documentation

artifacts:
  save_to: .claude/state/runs/{workflow_id}/
  include:
    - data-requirements.md
    - schema-design.md
    - migration.sql
    - drizzle-schema.ts
    - rls-policies.sql
    - indexes.sql
    - execution_log.json

estimated_duration: 5-10 minutes

success_criteria:
  - schema_design_complete
  - rls_policies_defined
  - indexes_created
  - migration_file_generated
  - drizzle_schema_updated

next_steps:
  - "Test migration locally: pnpm db:migrate:local"
  - "Deploy to production: pnpm db:migrate"
  - "Update application code to use new schema"
