-- ============================================================================
-- Migration: 016_add_productivity_tracking.sql
-- Description: Productivity tracking and Employee AI Twins infrastructure
-- Stories: AI-PROD-001, AI-PROD-002, AI-PROD-003, AI-TWIN-001
-- Author: InTime Development Team
-- Date: 2025-11-19
-- Epic: Epic 2.5 - AI Infrastructure (Sprint 4)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- ENUMS
-- ----------------------------------------------------------------------------

CREATE TYPE activity_category AS ENUM (
  'coding',
  'email',
  'meeting',
  'documentation',
  'research',
  'social_media',
  'idle'
);

CREATE TYPE employee_twin_role AS ENUM (
  'recruiter',
  'trainer',
  'bench_sales',
  'admin'
);

COMMENT ON TYPE activity_category IS 'Classification categories for employee activities';
COMMENT ON TYPE employee_twin_role IS 'Role types for personalized AI twins';

-- ----------------------------------------------------------------------------
-- TABLE: employee_screenshots
-- Description: Metadata for captured screenshots (AI-PROD-001)
-- Privacy: Employees see own; Admins see all
-- Retention: Auto-delete after 30 days
-- ----------------------------------------------------------------------------

CREATE TABLE employee_screenshots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Multi-tenancy
  org_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,

  -- Screenshot metadata
  filename TEXT NOT NULL, -- Format: {user_id}/{timestamp}.jpg
  file_size INTEGER NOT NULL, -- Bytes
  captured_at TIMESTAMPTZ NOT NULL,

  -- Classification results (AI-PROD-002)
  analyzed BOOLEAN DEFAULT FALSE,
  activity_category activity_category,
  confidence NUMERIC(3, 2), -- 0.00 to 1.00
  reasoning TEXT, -- AI's explanation

  -- Privacy flags
  is_sensitive BOOLEAN DEFAULT FALSE, -- Marked if sensitive window detected
  is_deleted BOOLEAN DEFAULT FALSE, -- Soft delete by user

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  deleted_at TIMESTAMPTZ -- Soft delete
);

-- Indexes
CREATE INDEX idx_screenshots_user_id ON employee_screenshots(user_id);
CREATE INDEX idx_screenshots_org_id ON employee_screenshots(org_id);
CREATE INDEX idx_screenshots_captured_at ON employee_screenshots(captured_at DESC);
CREATE INDEX idx_screenshots_analyzed ON employee_screenshots(analyzed) WHERE NOT analyzed;
CREATE INDEX idx_screenshots_category ON employee_screenshots(activity_category) WHERE activity_category IS NOT NULL;

-- Comments
COMMENT ON TABLE employee_screenshots IS 'Metadata for captured employee screenshots (productivity tracking)';
COMMENT ON COLUMN employee_screenshots.filename IS 'Storage path in Supabase Storage (employee-screenshots bucket)';
COMMENT ON COLUMN employee_screenshots.analyzed IS 'TRUE if AI has classified the activity';
COMMENT ON COLUMN employee_screenshots.is_sensitive IS 'TRUE if sensitive window was active (e.g., password manager)';

-- ----------------------------------------------------------------------------
-- TABLE: productivity_reports
-- Description: AI-generated daily productivity reports (AI-PROD-003)
-- Privacy: Employees see own; Managers see team aggregates
-- ----------------------------------------------------------------------------

CREATE TABLE productivity_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Multi-tenancy
  org_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,

  -- Report metadata
  date DATE NOT NULL,

  -- AI-generated content
  summary TEXT NOT NULL, -- Narrative overview of the day
  productive_hours NUMERIC(5, 2) NOT NULL, -- Hours spent on productive activities
  top_activities JSONB NOT NULL, -- [{category: 'coding', percentage: 45}, ...]
  insights JSONB NOT NULL, -- ['Pattern identified: Deep work 9-11am', ...]
  recommendations JSONB NOT NULL, -- ['Consider blocking calendar for focus time', ...]

  -- Raw metrics
  total_screenshots INTEGER NOT NULL DEFAULT 0,
  analyzed_screenshots INTEGER NOT NULL DEFAULT 0,
  activity_breakdown JSONB, -- {coding: 120, email: 45, meeting: 80, ...}

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  UNIQUE(user_id, date)
);

-- Indexes
CREATE INDEX idx_reports_user_date ON productivity_reports(user_id, date DESC);
CREATE INDEX idx_reports_org_date ON productivity_reports(org_id, date DESC);
CREATE INDEX idx_reports_date ON productivity_reports(date DESC);

-- Comments
COMMENT ON TABLE productivity_reports IS 'AI-generated daily productivity reports';
COMMENT ON COLUMN productivity_reports.summary IS 'Natural language summary of the day (generated by AI)';
COMMENT ON COLUMN productivity_reports.productive_hours IS 'Total hours spent on productive activities (coding, meetings, etc.)';
COMMENT ON COLUMN productivity_reports.top_activities IS 'Top 3 activities by time spent (JSON array)';

-- ----------------------------------------------------------------------------
-- TABLE: employee_twin_interactions
-- Description: Interaction history with Employee AI Twins (AI-TWIN-001)
-- Used for learning patterns and improving suggestions
-- ----------------------------------------------------------------------------

CREATE TABLE employee_twin_interactions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Multi-tenancy
  org_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,

  -- Twin context
  twin_role employee_twin_role NOT NULL,
  interaction_type TEXT NOT NULL, -- 'morning_briefing', 'suggestion', 'question', 'feedback'

  -- Content
  prompt TEXT, -- User's question or NULL for briefings
  response TEXT NOT NULL, -- AI's response
  context JSONB, -- Role-specific context used for response

  -- Quality metrics
  was_helpful BOOLEAN, -- User feedback (thumbs up/down)
  user_feedback TEXT, -- Optional text feedback

  -- AI model tracking
  model_used TEXT, -- 'gpt-4o-mini', 'gpt-4o', 'claude-sonnet-4-5'
  tokens_used INTEGER,
  cost_usd NUMERIC(10, 6), -- Cost in USD
  latency_ms INTEGER, -- Response time in milliseconds

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_twin_interactions_user_id ON employee_twin_interactions(user_id);
CREATE INDEX idx_twin_interactions_org_id ON employee_twin_interactions(org_id);
CREATE INDEX idx_twin_interactions_role ON employee_twin_interactions(twin_role);
CREATE INDEX idx_twin_interactions_type ON employee_twin_interactions(interaction_type);
CREATE INDEX idx_twin_interactions_created_at ON employee_twin_interactions(created_at DESC);
CREATE INDEX idx_twin_interactions_helpful ON employee_twin_interactions(was_helpful) WHERE was_helpful IS NOT NULL;

-- Comments
COMMENT ON TABLE employee_twin_interactions IS 'Interaction history with Employee AI Twins';
COMMENT ON COLUMN employee_twin_interactions.twin_role IS 'Which twin the user interacted with';
COMMENT ON COLUMN employee_twin_interactions.was_helpful IS 'User feedback on response quality';

-- ----------------------------------------------------------------------------
-- TABLE: twin_proactive_suggestions
-- Description: Scheduled proactive suggestions from AI Twins
-- Generated 3× per day based on activity patterns
-- ----------------------------------------------------------------------------

CREATE TABLE twin_proactive_suggestions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Multi-tenancy
  org_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,

  -- Twin context
  twin_role employee_twin_role NOT NULL,

  -- Suggestion content
  suggestion TEXT NOT NULL, -- The proactive suggestion
  reasoning TEXT, -- Why this suggestion was made
  priority TEXT NOT NULL DEFAULT 'medium', -- 'low', 'medium', 'high', 'critical'
  category TEXT, -- 'followup', 'deadline', 'opportunity', 'warning'

  -- Delivery
  delivered BOOLEAN DEFAULT FALSE,
  delivered_at TIMESTAMPTZ,
  dismissed BOOLEAN DEFAULT FALSE,
  dismissed_at TIMESTAMPTZ,
  actioned BOOLEAN DEFAULT FALSE, -- User took action
  actioned_at TIMESTAMPTZ,

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ -- Suggestion no longer relevant after this time
);

-- Indexes
CREATE INDEX idx_suggestions_user_id ON twin_proactive_suggestions(user_id);
CREATE INDEX idx_suggestions_org_id ON twin_proactive_suggestions(org_id);
CREATE INDEX idx_suggestions_delivered ON twin_proactive_suggestions(delivered) WHERE NOT delivered;
CREATE INDEX idx_suggestions_priority ON twin_proactive_suggestions(priority);
CREATE INDEX idx_suggestions_expires_at ON twin_proactive_suggestions(expires_at) WHERE NOT delivered;

-- Comments
COMMENT ON TABLE twin_proactive_suggestions IS 'Proactive suggestions generated by AI Twins';
COMMENT ON COLUMN twin_proactive_suggestions.suggestion IS 'The actionable suggestion text';
COMMENT ON COLUMN twin_proactive_suggestions.actioned IS 'TRUE if user took action on the suggestion';

-- ----------------------------------------------------------------------------
-- RLS POLICIES
-- ----------------------------------------------------------------------------

-- Enable RLS
ALTER TABLE employee_screenshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE productivity_reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE employee_twin_interactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE twin_proactive_suggestions ENABLE ROW LEVEL SECURITY;

-- employee_screenshots: Users see own; Admins see all in org
CREATE POLICY "Users can view own screenshots"
  ON employee_screenshots
  FOR SELECT
  USING (
    user_id = auth_user_id()
    AND org_id = auth_user_org_id()
  );

CREATE POLICY "Admins can view all screenshots in org"
  ON employee_screenshots
  FOR SELECT
  USING (
    org_id = auth_user_org_id()
    AND (user_is_admin() OR user_has_role('productivity_admin'))
  );

CREATE POLICY "Users can insert own screenshots"
  ON employee_screenshots
  FOR INSERT
  WITH CHECK (
    user_id = auth_user_id()
    AND org_id = auth_user_org_id()
  );

CREATE POLICY "Users can soft delete own screenshots"
  ON employee_screenshots
  FOR UPDATE
  USING (
    user_id = auth_user_id()
    AND org_id = auth_user_org_id()
  );

-- productivity_reports: Users see own; Managers see team
CREATE POLICY "Users can view own reports"
  ON productivity_reports
  FOR SELECT
  USING (
    user_id = auth_user_id()
    AND org_id = auth_user_org_id()
  );

CREATE POLICY "Managers can view team reports"
  ON productivity_reports
  FOR SELECT
  USING (
    org_id = auth_user_org_id()
    AND (
      user_is_admin()
      OR user_id = auth_user_id() -- Own report
      OR EXISTS (
        SELECT 1 FROM user_profiles
        WHERE id = productivity_reports.user_id
          AND employee_manager_id = auth_user_id()
      )
    )
  );

CREATE POLICY "System can insert reports"
  ON productivity_reports
  FOR INSERT
  WITH CHECK (
    org_id = auth_user_org_id()
  );

-- employee_twin_interactions: Users see own only
CREATE POLICY "Users can view own twin interactions"
  ON employee_twin_interactions
  FOR SELECT
  USING (
    user_id = auth_user_id()
    AND org_id = auth_user_org_id()
  );

CREATE POLICY "Users can insert own twin interactions"
  ON employee_twin_interactions
  FOR INSERT
  WITH CHECK (
    user_id = auth_user_id()
    AND org_id = auth_user_org_id()
  );

CREATE POLICY "Users can update own twin interactions"
  ON employee_twin_interactions
  FOR UPDATE
  USING (
    user_id = auth_user_id()
    AND org_id = auth_user_org_id()
  );

-- twin_proactive_suggestions: Users see own only
CREATE POLICY "Users can view own suggestions"
  ON twin_proactive_suggestions
  FOR SELECT
  USING (
    user_id = auth_user_id()
    AND org_id = auth_user_org_id()
  );

CREATE POLICY "System can insert suggestions"
  ON twin_proactive_suggestions
  FOR INSERT
  WITH CHECK (
    org_id = auth_user_org_id()
  );

CREATE POLICY "Users can update own suggestions"
  ON twin_proactive_suggestions
  FOR UPDATE
  USING (
    user_id = auth_user_id()
    AND org_id = auth_user_org_id()
  );

-- ----------------------------------------------------------------------------
-- FUNCTIONS
-- ----------------------------------------------------------------------------

-- Function: Auto-cleanup old screenshots (30 days retention)
CREATE OR REPLACE FUNCTION cleanup_old_screenshots()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  deleted_count INTEGER;
BEGIN
  -- Soft delete screenshots older than 30 days
  UPDATE employee_screenshots
  SET deleted_at = NOW(), is_deleted = TRUE
  WHERE captured_at < NOW() - INTERVAL '30 days'
    AND deleted_at IS NULL;

  GET DIAGNOSTICS deleted_count = ROW_COUNT;

  RETURN deleted_count;
END;
$$;

COMMENT ON FUNCTION cleanup_old_screenshots IS 'Auto-cleanup screenshots older than 30 days (privacy policy)';

-- Function: Get daily activity summary for user
CREATE OR REPLACE FUNCTION get_daily_activity_summary(
  p_user_id UUID,
  p_date DATE
)
RETURNS TABLE (
  total_screenshots BIGINT,
  analyzed_screenshots BIGINT,
  coding_count BIGINT,
  email_count BIGINT,
  meeting_count BIGINT,
  documentation_count BIGINT,
  research_count BIGINT,
  social_media_count BIGINT,
  idle_count BIGINT,
  productive_hours NUMERIC
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    COUNT(*) AS total_screenshots,
    COUNT(*) FILTER (WHERE analyzed = TRUE) AS analyzed_screenshots,
    COUNT(*) FILTER (WHERE activity_category = 'coding') AS coding_count,
    COUNT(*) FILTER (WHERE activity_category = 'email') AS email_count,
    COUNT(*) FILTER (WHERE activity_category = 'meeting') AS meeting_count,
    COUNT(*) FILTER (WHERE activity_category = 'documentation') AS documentation_count,
    COUNT(*) FILTER (WHERE activity_category = 'research') AS research_count,
    COUNT(*) FILTER (WHERE activity_category = 'social_media') AS social_media_count,
    COUNT(*) FILTER (WHERE activity_category = 'idle') AS idle_count,
    -- Calculate productive hours (30 seconds per screenshot)
    (
      COUNT(*) FILTER (
        WHERE activity_category IN ('coding', 'email', 'meeting', 'documentation', 'research')
      ) * 30.0 / 3600.0
    )::NUMERIC(5, 2) AS productive_hours
  FROM employee_screenshots
  WHERE user_id = p_user_id
    AND captured_at >= p_date::TIMESTAMPTZ
    AND captured_at < (p_date + INTERVAL '1 day')::TIMESTAMPTZ
    AND is_deleted = FALSE;
END;
$$;

COMMENT ON FUNCTION get_daily_activity_summary IS 'Get activity summary for a user on a specific date';

-- ----------------------------------------------------------------------------
-- TRIGGERS
-- ----------------------------------------------------------------------------

-- Trigger: Update updated_at timestamp
CREATE TRIGGER set_timestamp_employee_screenshots
BEFORE UPDATE ON employee_screenshots
FOR EACH ROW
EXECUTE FUNCTION trigger_set_timestamp();

CREATE TRIGGER set_timestamp_productivity_reports
BEFORE UPDATE ON productivity_reports
FOR EACH ROW
EXECUTE FUNCTION trigger_set_timestamp();

-- ----------------------------------------------------------------------------
-- VALIDATION VIEWS
-- ----------------------------------------------------------------------------

CREATE OR REPLACE VIEW v_productivity_tracking_status AS
SELECT
  'employee_screenshots' AS table_name,
  COUNT(*) AS total_records,
  COUNT(DISTINCT org_id) AS unique_orgs,
  COUNT(DISTINCT user_id) AS unique_users,
  COUNT(*) FILTER (WHERE analyzed = TRUE) AS analyzed_count,
  COUNT(*) FILTER (WHERE is_deleted = TRUE) AS soft_deleted_count
FROM employee_screenshots
UNION ALL
SELECT
  'productivity_reports' AS table_name,
  COUNT(*) AS total_records,
  COUNT(DISTINCT org_id) AS unique_orgs,
  COUNT(DISTINCT user_id) AS unique_users,
  NULL AS analyzed_count,
  NULL AS soft_deleted_count
FROM productivity_reports
UNION ALL
SELECT
  'employee_twin_interactions' AS table_name,
  COUNT(*) AS total_records,
  COUNT(DISTINCT org_id) AS unique_orgs,
  COUNT(DISTINCT user_id) AS unique_users,
  COUNT(*) FILTER (WHERE was_helpful = TRUE) AS helpful_count,
  NULL AS soft_deleted_count
FROM employee_twin_interactions
UNION ALL
SELECT
  'twin_proactive_suggestions' AS table_name,
  COUNT(*) AS total_records,
  COUNT(DISTINCT org_id) AS unique_orgs,
  COUNT(DISTINCT user_id) AS unique_users,
  COUNT(*) FILTER (WHERE actioned = TRUE) AS actioned_count,
  NULL AS soft_deleted_count
FROM twin_proactive_suggestions;

COMMENT ON VIEW v_productivity_tracking_status IS 'Validation view for productivity tracking data';

-- ----------------------------------------------------------------------------
-- COMPLETION MESSAGE
-- ----------------------------------------------------------------------------

DO $$
BEGIN
  RAISE NOTICE '============================================================';
  RAISE NOTICE 'Migration 016_add_productivity_tracking.sql completed successfully!';
  RAISE NOTICE '============================================================';
  RAISE NOTICE 'Changes:';
  RAISE NOTICE '  - Created activity_category ENUM';
  RAISE NOTICE '  - Created employee_twin_role ENUM';
  RAISE NOTICE '  - Created employee_screenshots table';
  RAISE NOTICE '  - Created productivity_reports table';
  RAISE NOTICE '  - Created employee_twin_interactions table';
  RAISE NOTICE '  - Created twin_proactive_suggestions table';
  RAISE NOTICE '  - Added RLS policies for all tables';
  RAISE NOTICE '  - Created cleanup_old_screenshots() function';
  RAISE NOTICE '  - Created get_daily_activity_summary() function';
  RAISE NOTICE '  - Created validation view v_productivity_tracking_status';
  RAISE NOTICE '============================================================';
  RAISE NOTICE 'Next Steps:';
  RAISE NOTICE '  1. Create Supabase Storage bucket: employee-screenshots';
  RAISE NOTICE '  2. Configure storage RLS policies';
  RAISE NOTICE '  3. Implement Electron desktop agent (AI-PROD-001)';
  RAISE NOTICE '  4. Implement ActivityClassifier service (AI-PROD-002)';
  RAISE NOTICE '  5. Implement TimelineGenerator service (AI-PROD-003)';
  RAISE NOTICE '  6. Implement EmployeeTwin framework (AI-TWIN-001)';
  RAISE NOTICE '============================================================';
END $$;
