-- Migration: Productivity Reports Table
-- Story: AI-PROD-003
-- Description: Daily timeline reports generated from classified screenshots

-- Productivity reports table
CREATE TABLE IF NOT EXISTS productivity_reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,
  date DATE NOT NULL,

  -- AI-generated narrative
  summary TEXT NOT NULL,
  productive_hours FLOAT NOT NULL,

  -- Structured data
  top_activities JSONB NOT NULL DEFAULT '[]'::jsonb,
  insights JSONB NOT NULL DEFAULT '[]'::jsonb,
  recommendations JSONB NOT NULL DEFAULT '[]'::jsonb,

  -- Metadata
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Ensure one report per user per day
  UNIQUE(user_id, date)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_productivity_reports_user_date
  ON productivity_reports(user_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_productivity_reports_date
  ON productivity_reports(date DESC);
CREATE INDEX IF NOT EXISTS idx_productivity_reports_user
  ON productivity_reports(user_id);

-- Row Level Security
ALTER TABLE productivity_reports ENABLE ROW LEVEL SECURITY;

-- Policy: Employees can see their own reports
CREATE POLICY reports_user_own ON productivity_reports
  FOR SELECT
  USING (user_id = auth.uid());

-- Policy: Managers can see their team's reports (future feature)
-- CREATE POLICY reports_manager_team ON productivity_reports
--   FOR SELECT
--   USING (
--     EXISTS (
--       SELECT 1 FROM user_profiles up
--       WHERE up.id = productivity_reports.user_id
--       AND up.manager_id = auth.uid()
--     )
--   );

-- Policy: Admins can see all reports
CREATE POLICY reports_admin_all ON productivity_reports
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON ur.role_id = r.id
      WHERE ur.user_id = auth.uid() AND r.name = 'admin'
    )
  );

-- Policy: System can insert/update reports
CREATE POLICY reports_system_insert ON productivity_reports
  FOR INSERT
  WITH CHECK (true); -- Service key only

CREATE POLICY reports_system_update ON productivity_reports
  FOR UPDATE
  USING (true); -- Service key only

-- Function: Update updated_at timestamp
CREATE OR REPLACE FUNCTION update_productivity_reports_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger: Auto-update updated_at
CREATE TRIGGER trigger_productivity_reports_updated_at
  BEFORE UPDATE ON productivity_reports
  FOR EACH ROW
  EXECUTE FUNCTION update_productivity_reports_updated_at();

-- Function: Get team productivity summary (future feature - requires manager_id column)
-- CREATE OR REPLACE FUNCTION get_team_productivity_summary(
--   p_manager_id UUID,
--   p_start_date DATE,
--   p_end_date DATE
-- )
-- RETURNS TABLE(
--   employee_id UUID,
--   employee_name TEXT,
--   avg_productive_hours FLOAT,
--   total_reports INTEGER,
--   top_activity TEXT
-- ) AS $$
-- BEGIN
--   RETURN QUERY
--   SELECT
--     pr.user_id as employee_id,
--     up.full_name as employee_name,
--     AVG(pr.productive_hours) as avg_productive_hours,
--     COUNT(*)::INTEGER as total_reports,
--     MODE() WITHIN GROUP (
--       ORDER BY (pr.top_activities->0->>'category')
--     ) as top_activity
--   FROM productivity_reports pr
--   JOIN user_profiles up ON pr.user_id = up.id
--   WHERE up.manager_id = p_manager_id
--     AND pr.date BETWEEN p_start_date AND p_end_date
--   GROUP BY pr.user_id, up.full_name;
-- END;
-- $$ LANGUAGE plpgsql SECURITY DEFINER;

-- Comment the table
COMMENT ON TABLE productivity_reports IS 'AI-generated daily productivity timelines for employees';
COMMENT ON COLUMN productivity_reports.summary IS 'Narrative daily summary generated by AI';
COMMENT ON COLUMN productivity_reports.productive_hours IS 'Total productive hours calculated from screenshots';
COMMENT ON COLUMN productivity_reports.top_activities IS 'Top 3 activities as JSON array';
COMMENT ON COLUMN productivity_reports.insights IS 'AI-generated insights as JSON array';
COMMENT ON COLUMN productivity_reports.recommendations IS 'AI-generated recommendations as JSON array';
