/**
 * HR Reports Screen Definition
 *
 * Metadata-driven screen for generating HR reports.
 */

import type { ScreenDefinition } from '@/lib/metadata';

// ==========================================
// OPTIONS
// ==========================================

const REPORT_CATEGORY_OPTIONS = [
  { value: 'compliance', label: 'Compliance' },
  { value: 'workforce', label: 'Workforce' },
  { value: 'payroll', label: 'Payroll' },
  { value: 'performance', label: 'Performance' },
  { value: 'benefits', label: 'Benefits' },
];

const REPORT_FORMAT_OPTIONS = [
  { value: 'pdf', label: 'PDF' },
  { value: 'excel', label: 'Excel' },
  { value: 'csv', label: 'CSV' },
];

// ==========================================
// SCREEN DEFINITION
// ==========================================

export const reportsScreen: ScreenDefinition = {
  id: 'hr-reports',
  type: 'dashboard',
  entityType: 'employee',

  title: 'HR Reports',
  subtitle: 'Generate and schedule HR reports',
  icon: 'FileText',

  // Layout
  layout: {
    type: 'single-column',
    sections: [
      // Report Categories
      {
        id: 'compliance-reports',
        type: 'info-card',
        title: 'Compliance Reports',
        fields: [
          { id: 'i9', label: 'I-9 Compliance Report', type: 'text', path: 'reports.i9' },
          { id: 'taxForms', label: 'Tax Form Status Report', type: 'text', path: 'reports.taxForms' },
          { id: 'backgroundChecks', label: 'Background Check Summary', type: 'text', path: 'reports.backgroundChecks' },
          { id: 'eeo', label: 'EEO-1 Report', type: 'text', path: 'reports.eeo' },
        ],
      },
      {
        id: 'workforce-reports',
        type: 'info-card',
        title: 'Workforce Reports',
        fields: [
          { id: 'headcount', label: 'Headcount Report', type: 'text', path: 'reports.headcount' },
          { id: 'turnover', label: 'Turnover Analysis', type: 'text', path: 'reports.turnover' },
          { id: 'timeToHire', label: 'Time to Hire', type: 'text', path: 'reports.timeToHire' },
          { id: 'demographics', label: 'Demographics Report', type: 'text', path: 'reports.demographics' },
        ],
      },
      {
        id: 'payroll-reports',
        type: 'info-card',
        title: 'Payroll Reports',
        fields: [
          { id: 'payrollSummary', label: 'Payroll Summary by Period', type: 'text', path: 'reports.payrollSummary' },
          { id: 'overtime', label: 'Overtime Analysis', type: 'text', path: 'reports.overtime' },
          { id: 'ptoAccrual', label: 'PTO Accrual Report', type: 'text', path: 'reports.ptoAccrual' },
          { id: 'laborCost', label: 'Labor Cost Report', type: 'text', path: 'reports.laborCost' },
        ],
      },
      {
        id: 'performance-reports',
        type: 'info-card',
        title: 'Performance Reports',
        fields: [
          { id: 'reviewStatus', label: 'Performance Review Status', type: 'text', path: 'reports.reviewStatus' },
          { id: 'goalCompletion', label: 'Goal Completion Rate', type: 'text', path: 'reports.goalCompletion' },
          { id: 'pipSummary', label: 'PIP Summary', type: 'text', path: 'reports.pipSummary' },
          { id: 'ratings', label: 'Rating Distribution', type: 'text', path: 'reports.ratings' },
        ],
      },
      // Scheduled Reports
      {
        id: 'scheduled-reports',
        type: 'table',
        title: 'Scheduled Reports',
        columns_config: [
          { id: 'name', label: 'Report Name', path: 'name', type: 'text' },
          {
            id: 'category',
            label: 'Category',
            path: 'category',
            type: 'enum',
            config: {
              options: REPORT_CATEGORY_OPTIONS,
              badgeColors: { compliance: 'blue', workforce: 'green', payroll: 'purple', performance: 'orange', benefits: 'cyan' },
            },
          },
          { id: 'frequency', label: 'Frequency', path: 'frequency', type: 'text' },
          { id: 'nextRun', label: 'Next Run', path: 'nextRunDate', type: 'date' },
          { id: 'recipients', label: 'Recipients', path: 'recipientCount', type: 'number' },
          { id: 'lastRun', label: 'Last Run', path: 'lastRunDate', type: 'date' },
        ],
        dataSource: {
          type: 'list',
          entityType: 'employee',
        },
      },
      // Recent Reports
      {
        id: 'recent-reports',
        type: 'table',
        title: 'Recently Generated',
        columns_config: [
          { id: 'name', label: 'Report Name', path: 'name', type: 'text' },
          { id: 'generatedAt', label: 'Generated', path: 'generatedAt', type: 'date' },
          { id: 'generatedBy', label: 'Generated By', path: 'generatedBy.fullName', type: 'text' },
          {
            id: 'format',
            label: 'Format',
            path: 'format',
            type: 'enum',
            config: { options: REPORT_FORMAT_OPTIONS },
          },
          { id: 'size', label: 'Size', path: 'fileSizeLabel', type: 'text' },
        ],
        dataSource: {
          type: 'list',
          entityType: 'employee',
          sort: { field: 'generatedAt', direction: 'desc' },
          limit: 10,
        },
      },
    ],
  },

  // Header actions
  actions: [
    {
      id: 'generate',
      label: 'Generate Report',
      type: 'modal',
      variant: 'primary',
      icon: 'FileText',
      config: {
        type: 'modal',
        modal: 'GenerateReportModal',
      },
    },
    {
      id: 'schedule',
      label: 'Schedule Report',
      type: 'modal',
      variant: 'secondary',
      icon: 'Calendar',
      config: {
        type: 'modal',
        modal: 'ScheduleReportModal',
      },
    },
  ],

  // Navigation
  navigation: {
    back: { label: 'Back to Dashboard', route: '/employee/hr' },
    breadcrumbs: [
      { label: 'HR', route: '/employee/hr' },
      { label: 'Reports' },
    ],
  },
};

export default reportsScreen;
